### PR TITLE
CASMINST-3421 CASMINST-6410 Add `noos` repo

### PR DESCRIPTION
**Pull request by rustydb**
This adds the `noos` repo, and moves one of the first packages to publish there into it (`platform-utils`).

### CODE REVIEW

**Review by phalseth-hpe — APPROVED** [review]

**Comment by phalseth-hpe** [comment]
I don't think this PR is related CASMINST-3421. Can you update the title with the correct ticket number?

**Comment by rustydb** [comment]
@phalseth-hpe it does add noos though 🤷

**Comment by rustydb** [comment]
I see this got backported to stable, the new images won't be built for stable though since this is a very trivial change.

**Pull request merged**
