### PR TITLE
CASMCMS-7722 Update IMS to version v3.4.7

### PR DESCRIPTION
**Pull request by ecozzi-hpe**
## Summary and Scope

Update IMS to version v3.4.7

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_ Yes

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [CASMCMS-7722](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7722)
* Resolves [CASMCMS-7728](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7728)
* 
## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `Hela`

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? No
- Were continuous integration tests run? If not, why? No
- Was upgrade tested? If not, why? Yes
- Was downgrade tested? If not, why? Yes
- Were new tests (or test issues/Jiras) created for this change? No

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_
None

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable
- [x] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

### CODE REVIEW

**Comment by mtupitsyn** [comment]
@ecozzi-hpe I think there may be a typo in Chart.yaml for new cray-ims helm chart version 3.4.5. The `artifacthub.io/images` annotation is now referring to non-existing image `artifactory.algol60.net/csm-docker/stable/cray-ims-service` of version `1.5.7`. This version does not exist, all existing versions of this image belong to 3.x.x range. it was referring to `3.4.3` in previous version of chart.

```
$ diff -U 5  cray-ims-3.4.3/Chart.yaml cray-ims-3.4.5/Chart.yaml
--- cray-ims-3.4.3/Chart.yaml	2021-12-07 09:00:42.000000000 -0800
+++ cray-ims-3.4.5/Chart.yaml	2021-12-16 09:11:38.000000000 -0800
@@ -1,23 +1,23 @@
 annotations:
   artifacthub.io/images: |
     - name: cray-ims-service
-      image: artifactory.algol60.net/csm-docker/stable/cray-ims-service:3.4.3
+      image: artifactory.algol60.net/csm-docker/stable/cray-ims-service:1.5.7
                                                                         ^^^^^
     - name: cray-ims-utils
-      image: artifactory.algol60.net/csm-docker/stable/cray-ims-utils:2.6.76
+      image: artifactory.algol60.net/csm-docker/stable/cray-ims-utils:2.6.78
...
```

**Comment by mtupitsyn** [comment]
FYI - issue is described and mitigated as https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7728. This PR will likely need a rebase after fix for CASMCMS-7728 lands.

**Comment by ecozzi-hpe** [comment]
Updated the manifest after @mharding-hpe fixed the above issue in CASMCMS-7728. The manifest now is updating the IMS version to 3.4.7

**Review by mharding-hpe — COMMENTED** [review]
Looks good to me.

**Pull request merged**
