### PR TITLE
CRAYSAT-1774: Add cray-sat-podman RPM to noos repository

### PR DESCRIPTION
**Pull request by haasken-hpe**
## Summary and Scope

This package was part of the SAT product stream and is being added to the CSM product stream to merge the SAT product into CSM fully.

Technically this package is also already installed in the Kubernetes management NCN images, but it seems like a good idea to keep including it in a Nexus package repository like SAT does today. This would enable updates of this package if needed without updating the management NCN images.

## Issues and Related PRs

* Resolves [CRAYSAT-1774](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1774)
* Merge after https://github.com/Cray-HPE/sat-podman/pull/34
* Also wait for a stable build of cray-sat-podman to be produced

### Tested on:

  * Jenkins

### Test description:

The Jenkins build should validate that the RPM can be downloaded from the location specified in the `index.yaml` manifest file.

## Risks and Mitigations

Pretty low-risk as it's just adding an RPM that used to be provided by the SAT product to the CSM product.

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] Testing is appropriate and complete, if applicable
- [x] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

### CODE REVIEW

**Comment by haasken-hpe** [comment]
I've created this PR as a draft until I have merged the associated sat-podman PR and created the stable release.

**Comment by haasken-hpe** [comment]
The associated sat-podman PR (https://github.com/Cray-HPE/sat-podman/pull/34) was merged, and the `release/2.1` branch was created to create the stable build 2.1.0-1, so this is ready for review and merge now.

**Comment by heemstra** [comment]
Since `cray-sat-podman` is embedded in the NCN images (by way of the metal-provision repo), it doesn't need to be added to a manifest file in the csm repo.  Part of the CSM release build process is to fetch every rpm installed on the NCN images and create an embedded repo containing all of these packages.  This then gets configured via CFS as the "CSM Embedded NCN Packages" repository.

E.g. on fanta running CSM-1.5:
```
ncn-m001:~ # zypper se -v cray-sat-podman
Loading repository data...
Reading installed packages...

S  | Name            | Type    | Version | Arch   | Repository
---+-----------------+---------+---------+--------+---------------------------------------------
i+ | cray-sat-podman | package | 2.0.0-1 | x86_64 | CSM Embedded NCN Packages (added by Ansible)
    name: cray-sat-podman

    Note: For an extended search including not yet activated remote resources please use 'zypper
    search-packages'.
ncn-m001:~ #
```

**Comment by haasken-hpe** [comment]
Closing based on John's comment. I will be opening a separate PR to update the version of cray-sat-podman used in the metal-provision repo and to remove the sat-rpms repo from use.

**Pull request closed without merging**
